[[service]]
name = "example-active"
exec = "/bin/example-active"
args = ["arg1", "arg2"]
restart = true

[[service]]
name = "example-inactive"
exec = "/bin/example-inactive"
args = ["arg1", "arg2"]
restart = false
